"""added data tables

Revision ID: 37e4a30e62dc
Revises: 
Create Date: 2025-11-24 17:25:00.242123

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e4a30e62dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geo_lv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_abv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_full', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('var_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name_abv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_full', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_interm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_table.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geo_table.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_interm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_table.id'], ),
    sa.ForeignKeyConstraint(['var_id'], ['variable_table.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('name_abv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_full', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name_full', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name_full', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    op.drop_table('county')
    op.drop_table('states')
    op.drop_table('variable_interm')
    op.drop_table('geo_interm')
    op.drop_table('divisions')
    op.drop_table('year_table')
    op.drop_table('variable_table')
    op.drop_table('regions')
    op.drop_table('geo_table')
    op.drop_table('dataset_table')
    # ### end Alembic commands ###
