"""added data tables

Revision ID: 83bda86e2b2f
Revises: 8e535d5d6953
Create Date: 2025-11-11 09:02:55.977746

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bda86e2b2f'
down_revision: Union[str, Sequence[str], None] = '8e535d5d6953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicate_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predicate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_interm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('interm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geo_id'], ['geo_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cconcept_id', sa.Integer(), nullable=False),
    sa.Column('required_id', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('predicate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cconcept_id'], ['concept_table.id'], ),
    sa.ForeignKeyConstraint(['predicate_id'], ['predicate_table.id'], ),
    sa.ForeignKeyConstraint(['required_id'], ['required_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year_interm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('interm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['year_id'], ['year_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_interm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interm_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['var_id'], ['variable_table.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_interm_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('geo_interm_id', sa.Integer(), nullable=False),
    sa.Column('var_interm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geo_interm_id'], ['geo_interm.interm_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['dataset_type.id'], ),
    sa.ForeignKeyConstraint(['var_interm_id'], ['variable_interm.interm_id'], ),
    sa.ForeignKeyConstraint(['year_interm_id'], ['year_interm.interm_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('variable_interm')
    op.drop_table('year_interm')
    op.drop_table('variable_table')
    op.drop_table('geo_interm')
    op.drop_table('year_table')
    op.drop_table('required_table')
    op.drop_table('predicate_table')
    op.drop_table('geo_table')
    op.drop_table('dataset_type')
    op.drop_table('concept_table')
    # ### end Alembic commands ###
