"""added data tables2

Revision ID: 8ba74e16e280
Revises: 86428097f597
Create Date: 2025-11-22 19:47:37.485309

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba74e16e280'
down_revision: Union[str, Sequence[str], None] = '86428097f597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls_table', sa.Column('dataset', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('urls_table', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls_table', sa.Column('title', sa.VARCHAR(), nullable=False))
    op.drop_column('urls_table', 'dataset')
    # ### end Alembic commands ###
